### ISSUE TITLE
Error when importing tiles with < and >

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/Tilesheets#56]
```
Exception encountered, of type "TypeError"
[9d263bf59c5102e2cc29954f] /Special:CreateTileSheet TypeError from line 501 of /home/hydra/stable_public_html/includes/logging/LogEntry.php: Argument 1 passed to ManualLogEntry::setTarget() must be an instance of Title, null given, called in /home/hydra/stable_public_html/extensions/Tilesheets/special/TileManager.php on line 107
Backtrace:
#0 /home/hydra/stable_public_html/extensions/Tilesheets/special/TileManager.php(107): ManualLogEntry->setTarget(NULL)
#1 /home/hydra/stable_public_html/extensions/Tilesheets/special/CreateTileSheet.php(87): TileManager::createTile(string, string, string, string, User, string)
#2 /home/hydra/stable_public_html/includes/specialpage/SpecialPage.php(479): CreateTileSheet->execute(NULL)
#3 /home/hydra/stable_public_html/includes/specialpage/SpecialPageFactory.php(576): SpecialPage->run(NULL)
#4 /home/hydra/stable_public_html/includes/MediaWiki.php(282): SpecialPageFactory::executePath(Title, RequestContext)
#5 /home/hydra/stable_public_html/includes/MediaWiki.php(745): MediaWiki->performRequest()
#6 /home/hydra/stable_public_html/includes/MediaWiki.php(519): MediaWiki->main()
#7 /home/hydra/stable_public_html/index.php(43): MediaWiki->run()
#8 {main}
```

For example, `MFDevice <Debugger>`.

**Comment by Alexia** [comment]
From includes/DefaultSettings.php:

```
 * Problematic punctuation:
 *   -  []{}|#    Are needed for link syntax, never enable these
 *   -  <>        Causes problems with HTML escaping, don't use
 *   -  %         Enabled by default, minor problems with path to query rewrite rules, see below
 *   -  +         Enabled by default, but doesn't work with path to query rewrite rules,
 *                corrupted by apache
 *   -  ?         Enabled by default, but doesn't work with path to PATH_INFO rewrites
```

I would recommend moving "Title::newFromText("Tile/$target", NS_SPECIAL)" to the top of TileManager::createTile() assigned to its own variable and having the function return false if the title returned is null.

**Comment by elifoster** [comment]
Those would work, except that what is invalid for a title isn't necessarily invalid for a tile. In this case, <> can be in a tile name no problem, as long as you import it as one thing then rename it in the tile manager.

**Comment by elifoster** [comment]
It probably makes more sense to have that title set to Tile/entry id

**Comment by elifoster** [comment]
So with the tile translation system, being able to use weird characters is less of an issue. If someone has a tile `< Some weird thing >[]{}|` they can always just add it as `Some weird thing` and then translate it to `< Some weird thing >[]{}|`. See: #72.
